<?php

namespace Dcat\Admin\Form;

use Dcat\Admin\Actions\Action;
use Dcat\Admin\Form;

abstract class AbstractTool extends Action
{
    /**
     * @var Form
     */
    protected Form $parent;

    /**
     * @var string
     */
    protected string $style = 'btn btn-sm btn-primary';

    /**
     * Whether the action should only allow in creation page.
     *
     * @var bool
     */
    public bool $allowOnlyCreating = false;

    /**
     * Whether the action should only allow in edit page.
     *
     * @var bool
     */
    public bool $allowOnlyEditing = false;

    /**
     * @param  Form  $form
     * @return void
     */
    public function setForm(Form $form): void
    {
        $this->parent = $form;
    }

    /**
     * @return array|string
     */
    public function getKey(): array|string
    {
        if ($this->primaryKey) {
            return $this->primaryKey;
        }

        return $this->parent ? $this->parent->getKey() : '';
    }

    /**
     * @return string
     */
    public function render(): string
    {
        if ($this->allowOnlyEditing && ! $this->parent->isEditing()) {
            return '';
        }

        if ($this->allowOnlyCreating && ! $this->parent->isCreating()) {
            return '';
        }

        return parent::render(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function setupHtmlAttributes(): void
    {
        $this->addHtmlClass($this->style);

        parent::setupHtmlAttributes();
    }

    /**
     * @param  mixed  ...$params
     * @return $this
     */
    public static function allowOnlyCreating(...$params): static
    {
        $tool = static::make(...$params);

        $tool->allowOnlyCreating = true;
        $tool->allowOnlyEditing  = false;

        return $tool;
    }

    /**
     * @param  mixed  ...$params
     * @return $this
     */
    public static function allowOnlyEditing(...$params): static
    {
        $tool = static::make(...$params);

        $tool->allowOnlyEditing  = true;
        $tool->allowOnlyCreating = false;

        return $tool;
    }
}
