<?php

namespace Dcat\Admin\Widgets;

use Dcat\Admin\Support\Helper;
use Illuminate\Contracts\Support\Arrayable;
use Illuminate\Support\Str;

class Tree extends Widget
{
    protected string $view = 'admin::widgets.tree';

    protected array $options = [
        'plugins' => ['checkbox', 'types'],
        'core' => [
            'check_callback' => true,

            'themes' => [
                'name' => 'proton',
                'responsive' => true,
            ],
        ],
        'checkbox' => [
            'keep_selected_style' => false,
        ],
        'types' => [
            'default' => [
                'icon' => false,
            ],
        ],
    ];

    protected string $id = '';

    protected array $columnNames = [
        'id' => 'id',
        'text' => 'name',
        'parent' => 'parent_id',
    ];

    protected array $nodes = [];

    protected array $value = [];

    protected bool $checkAll = false;

    public function __construct($nodes = [])
    {
        $this->nodes($nodes);

        $this->id = 'widget-tree-'.Str::random(8);
    }

    public function checkAll(): static
    {
        $this->checkAll = true;

        return $this;
    }

    public function check($value): static
    {
        $this->value = Helper::array($value);

        return $this;
    }

    public function setIdColumn(string $name): static
    {
        $this->columnNames['id'] = $name;

        return $this;
    }

    public function setTitleColumn(string $name): static
    {
        $this->columnNames['text'] = $name;

        return $this;
    }

    public function setParentColumn(string $name): static
    {
        $this->columnNames['parent'] = $name;

        return $this;
    }

    /**
     * @param  array|Arrayable  $data
     * @return $this
     */
    public function nodes(array|Arrayable $data): static
    {
        if ($data instanceof Arrayable) {
            $data = $data->toArray();
        }
        $this->nodes = &$data;

        return $this;
    }

    public function render(): string
    {
        $this->id($this->id);
        $this->class('jstree-wrapper');
        $this->defaultHtmlAttribute('style', 'border:0;padding:5px 0');

        $this->formatNodes();

        $this->variables = [
            'id' => $this->id,
            'nodes' => &$this->nodes,
        ];

        return parent::render(); // TODO: Change the autogenerated stub
    }

    protected function formatNodes(): void
    {
        $value = $this->value;
        if ($value && !is_array($value)) {
            $value = explode(',', $value);
        }

        if (!$this->nodes) {
            return;
        }

        $idColumn = $this->columnNames['id'];
        $textColumn = $this->columnNames['text'];
        $parentColumn = $this->columnNames['parent'];

        $nodes = [];

        foreach ($this->nodes as &$v) {
            if (empty($v[$idColumn])) {
                continue;
            }

            $parentId = $v[$parentColumn] ?? '#';
            if (empty($parentId)) {
                $parentId = '#';
            }

            $v['state'] = [];

            if ($this->checkAll || ($value && in_array($v[$idColumn], $value))) {
                $v['state']['selected'] = true;
            }

            $v['state']['disabled'] = true;

            $nodes[] = [
                'id' => $v[$idColumn],
                'text' => $v[$textColumn] ?? null,
                'parent' => $parentId,
                'state' => $v['state'],
            ];
        }

        $this->nodes = &$nodes;
    }
}
