<?php

namespace Dcat\Admin\Console;

use Illuminate\Contracts\Filesystem\FileNotFoundException;
use Psr\Container\ContainerExceptionInterface;
use Psr\Container\NotFoundExceptionInterface;
use ReflectionException;

class FormCommand extends GeneratorCommand
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $signature = 'admin:form {name}
        {--namespace=}
        {--base=}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Make admin form widget';

    /**
     * @return bool|null
     *
     * @throws FileNotFoundException
     * @throws ContainerExceptionInterface
     * @throws NotFoundExceptionInterface
     * @throws ReflectionException
     */
    public function handle(): ?bool
    {
        $this->askBaseDirectory();

        return parent::handle(); // TODO: Change the autogenerated stub
    }

    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub(): string
    {
        return __DIR__.'/stubs/form.stub';
    }

    /**
     * Get the default namespace for the class.
     *
     * @param  string  $rootNamespace
     * @return string
     */
    protected function getDefaultNamespace(string $rootNamespace): string
    {
        if ($namespace = $this->option('namespace')) {
            return $namespace;
        }

        return str_replace('Controllers', 'Forms', config('admin.route.namespace'));
    }

    /**
     * Get the desired class name from the input.
     *
     * @return string
     */
    protected function getNameInput(): string
    {
        $name = trim($this->argument('name'));

        $this->type = $this->qualifyClass($name);

        return $name;
    }
}
